# Generated by Django 4.1.3 on 2022-12-07 12:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChecksInside',
            fields=[
                ('check_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=16, unique=True)),
                ('balance', models.FloatField()),
                ('csv', models.CharField(max_length=3)),
                ('limit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('short_name', models.CharField(max_length=3)),
                ('in_rubs', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=5)),
                ('reg_date', models.DateField()),
                ('blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('op_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('receive_number', models.CharField(max_length=16)),
                ('receive_full_name', models.CharField(max_length=50)),
                ('sent_money', models.FloatField()),
                ('comission', models.FloatField()),
                ('date', models.DateTimeField()),
                ('receive_bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.banks')),
                ('received_money', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.currencies')),
                ('send_check_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.checksinside')),
            ],
        ),
        migrations.AddField(
            model_name='checksinside',
            name='currency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.currencies'),
        ),
        migrations.AddField(
            model_name='checksinside',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.users'),
        ),
        migrations.AddField(
            model_name='banks',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.countries'),
        ),
        migrations.CreateModel(
            name='Actives',
            fields=[
                ('active_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active_type', models.CharField(max_length=20)),
                ('balance', models.FloatField()),
                ('date', models.DateField()),
                ('term', models.IntegerField()),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.banks')),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.currencies')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
            ],
        ),
    ]
