# Generated by Django 4.1.3 on 2022-12-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChecksInside',
            new_name='Checks',
        ),
    ]
