# Generated by Django 4.1.3 on 2022-12-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_checksinside_checks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actives',
            new_name='Active',
        ),
        migrations.RenameModel(
            old_name='Banks',
            new_name='Bank',
        ),
        migrations.RenameModel(
            old_name='Checks',
            new_name='Check',
        ),
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
        migrations.RenameModel(
            old_name='Currencies',
            new_name='Currency',
        ),
        migrations.RenameModel(
            old_name='Operations',
            new_name='Operation',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
